/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../../models/components";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class SuggestedTopicsRequest extends SpeakeasyBase {
    /**
     * Page number of results to return. Defaults to 1.<br />
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=page" })
    page?: number;

    /**
     * Number of results to return per page. Defaults to 20.<br />
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=per_page" })
    perPage?: number;
}

/**
 * conversation
 */
export class SuggestedTopicsResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "pagination" })
    @Type(() => components.Pagination)
    pagination: components.Pagination;

    @SpeakeasyMetadata({ elemType: components.TopicWithSamples })
    @Expose({ name: "topics" })
    @Type(() => components.TopicWithSamples)
    topics: components.TopicWithSamples[];
}

export class SuggestedTopicsResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * conversation
     */
    @SpeakeasyMetadata()
    object?: SuggestedTopicsResponseBody;
}
