/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { MessageParams } from "./messageparams";
import { Expose, Type } from "class-transformer";

export class ConversationParams extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: MessageParams })
    @Expose({ name: "messages" })
    @Type(() => MessageParams)
    messages?: MessageParams[];

    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: Record<string, string>;
}
