/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Conversation } from "./conversation";
import { Expose, Type } from "class-transformer";

export class TopicWithSamples extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Conversation })
    @Expose({ name: "conversations_sample" })
    @Type(() => Conversation)
    conversationsSample: Conversation[];

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;
}
